title: whitestarrain's blog
author: whitestarrain
email: kaneki.lusou@gmail.com
description: > # this means to ignore newlines until "show_exerpts:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
show_excerpts: true # set to true to show excerpts on the homepage
baseurl: "/blog"  # 本地访问时要删除

# Minima date format
# refer to http://shopify.github.io/liquid/filters/date/ if you want to customize this
sass:
  sass_dir: _sass

paginate: 7
paginate_path: "/page:num"

permalink: /posts/:title/
texture:
  title: whitestarrain's blog
  tagline: Relaxation is the source of strength for effort
  date_format: "%b %-d, %Y"
  style: black
  showNav: true
  show_excerpts: true
  navigation:
    - title: home
      url: "/blog/"
    - title: My Work
      url: "/blog/"
    - title: Resume
      url: "/blog/"
    - title: archives
      url: "/blog/archives/"
    - title: tags
      url: "/blog/tags/"

  # generate social links in footer
  social_links:
    twitter: https://twitter.com/qS5DNI9AnIqygQs
    github:  https://github.com/whitestarrain
    linkedIn: 
    rss: rss


# If you want to link only specific pages in your header, uncomment
# this and add the path to the pages in order as they should show up
#header_pages:
# - about.md

# Build settings
# theme: texture

plugins:
  - jekyll-seo-tag
  - jekyll-paginate # 分页插件
  - jekyll-toc  # toc插件


toc:
  min_level: 1
  max_level: 6
  no_toc_section_class: no_toc_section
  list_class: section-nav shadow
  sublist_class: ''
  item_class: toc-entry
  item_prefix: toc-