title: whitestarrain's blog
author: whitestarrain
email: kaneki.lusou@gmail.com
description: > # this means to ignore newlines until "show_exerpts:"
  A growing programmer. The development direction is big data processing, mainly
  using java and python. Both node.js and c++ are involved but there is no special in-depth study. As
  a back-end programmer, but also have a soft spot for the front end<
show_excerpts: true # set to true to show excerpts on the homepage
baseurl: "/blog"  # 本地访问时要删除

# Minima date format
# refer to http://shopify.github.io/liquid/filters/date/ if you want to customize this
sass:
  sass_dir: _sass

paginate: 7
paginate_path: "/page:num"

permalink: /posts/:title/
texture:
  title: whitestarrain's blog
  tagline: Relaxation is the source of strength for effort
  date_format: "%b %-d, %Y"
  style: black
  showNav: true
  show_excerpts: true
  navigation:
    - title: Home
      url: "/blog/"
    - title: My Work
      url: "/blog/"
    - title: Resume
      url: "/blog/"
    - title: Archives
      url: "/blog/archives/"
    - title: Tags
      url: "/blog/tags/"

  # generate social links in footer
  social_links:
    twitter: https://twitter.com/qS5DNI9AnIqygQs
    github:  https://github.com/whitestarrain
    linkedIn: 
    rss: rss

excerpt_separator: <!-- more -->

# If you want to link only specific pages in your header, uncomment
# this and add the path to the pages in order as they should show up
#header_pages:
# - about.md

# Build settings
# theme: texture

plugins:
  - jekyll-seo-tag
  - jekyll-paginate # 分页插件
  - jekyll-sitemap

